
@extends('admin.layouts.master')

@push('styles')
<style>
    @media print {
        /* Hide non-essential UI elements */
        .main-sidebar, 
        .main-navbar, 
        .navbar, 
        .main-footer, 
        .section-header, 
        .btn, 
        .card-icon {
            display: none !important;
        }

        /* Reset layout for printing */
        .main-content {
            padding: 0 !important;
            margin: 0 !important;
            width: 100% !important;
        }

        body, .main-wrapper {
            background-color: white !important;
            color: black !important;
        }

        .section {
            padding: 0 !important;
        }

        /* Card adjustments for print */
        .card {
            border: 1px solid #eee !important;
            box-shadow: none !important;
            break-inside: avoid;
            margin-bottom: 20px !important;
        }

        .card-statistic-1 {
            border: 1px solid #ddd !important;
        }

        .agent-card {
            border: 1px solid #ddd !important;
            page-break-inside: avoid;
        }

        /* Table adjustments */
        table {
            width: 100% !important;
            border-collapse: collapse !important;
        }
        
        th, td {
            border: 1px solid #ddd !important;
            padding: 8px !important;
        }

        /* Show the print-only header */
        .print-header {
            display: block !important;
            margin-bottom: 30px;
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        
        .print-date {
            font-size: 0.9rem;
            color: #666;
        }
    }

    /* Hide print header on screen */
    .print-header {
        display: none;
    }
</style>
@endpush

@section('contents')
  <section class="section">
    <!-- Print Only Header (Enhanced) -->
    <div class="print-header">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
            <div style="text-align: left;">
                <h1 style="margin: 0; color: #1a1a1a; font-size: 28px; font-weight: 800; letter-spacing: -1px;">TRUCKZAP</h1>
                <p style="margin: 0; color: #666; font-size: 14px; font-weight: 600;">Quality Control & Performance Analytics</p>
            </div>
            <div style="text-align: right;">
                <h2 style="margin: 0; color: #333; font-size: 20px;">Monthly Performance Report</h2>
                <p class="print-date" style="margin: 0;">Period: {{ now()->format('F Y') }}</p>
            </div>
        </div>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; border: 1px solid #eee; margin-bottom: 30px; text-align: left;">
            <p style="margin: 0; font-size: 12px; color: #555;">This document contains sensitive performance data for internal review. Generated by <strong>{{ Auth::user()->name }}</strong> on {{ now()->format('m/d/Y h:i A') }}</p>
        </div>
    </div>

    <div class="section-header">
      <h1>AI Agent Dashboard</h1>
      <div class="section-header-breadcrumb print:hidden">
        
      </div>
    </div>
    
    <!-- Stats Row -->
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
          <div class="card-icon bg-primary">
            <i class="fas fa-phone"></i>
          </div>
          <div class="card-wrap">
            <div class="card-header">
              <h4>Total </h4>
            </div>
            <div class="card-body">
          
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
          <div class="card-icon bg-success">
            <i class="fas fa-check-circle"></i>
          </div>
          <div class="card-wrap">
            <div class="card-header">
              <h4>Scored </h4>
            </div>
            <div class="card-body">
              
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
          <div class="card-icon bg-warning">
            <i class="fas fa-hourglass-half"></i>
          </div>
          <div class="card-wrap">
            <div class="card-header">
              <h4>Pending Review</h4>
            </div>
            <div class="card-body">
             
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
          <div class="card-icon bg-info">
            <i class="fas fa-comments"></i>
          </div>
          <div class="card-wrap">
            <div class="card-header">
              <h4>Total </h4>
            </div>
            <div class="card-body">
            
            </div>
          </div>
        </div>
      </div>
    </div>

  

  </section>
@endsection